### ISSUE TITLE
OSError: [Errno 121] Unable to open file

### ISSUE THREAD

**Issue by dmacguigan** [linguoliang/puzzle-hi-c#3]
Thank you for developing a new scaffolding tool! 

I just tried running your script using my own dataset (which I have used successfully with 3D-DNA). However, I encountered the following error message.

```
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/projects/academic/tkrabben/modules_KrabLab/easybuild/2023.01/software/Core/miniconda3/22.11.1-1/envs/puzzle-hi-c-deps/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/projects/academic/tkrabben/modules_KrabLab/easybuild/2023.01/software/Core/miniconda3/22.11.1-1/envs/puzzle-hi-c-deps/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/projects/academic/tkrabben/software/puzzle-hi-c/main.py", line 88, in read_gloable_repeat_density
    with h5py.File("tmp/repeat_dict.h5", "r") as repeat_h5:
  File "/projects/academic/tkrabben/modules_KrabLab/easybuild/2023.01/software/Core/miniconda3/22.11.1-1/envs/puzzle-hi-c-deps/lib/python3.9/site-packages/h5py/_hl/files.py", line 533, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/projects/academic/tkrabben/modules_KrabLab/easybuild/2023.01/software/Core/miniconda3/22.11.1-1/envs/puzzle-hi-c-deps/lib/python3.9/site-packages/h5py/_hl/files.py", line 226, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 106, in h5py.h5f.open
OSError: [Errno 121] Unable to open file (unable to lock file, errno = 121, error message = 'Remote I/O error')
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/projects/academic/tkrabben/software/puzzle-hi-c/main.py", line 1318, in <module>
    pool.map(read_gloable_repeat_density, list_temp_names)
  File "/projects/academic/tkrabben/modules_KrabLab/easybuild/2023.01/software/Core/miniconda3/22.11.1-1/envs/puzzle-hi-c-deps/lib/python3.9/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/projects/academic/tkrabben/modules_KrabLab/easybuild/2023.01/software/Core/miniconda3/22.11.1-1/envs/puzzle-hi-c-deps/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
OSError: [Errno 121] Unable to open file (unable to lock file, errno = 121, error message = 'Remote I/O error')

```

Since I do not have pip on this computing cluster, I installed all of the necessary dependencies in a conda environment.

```
(puzzle-hi-c-deps) dmacguig@vortex-future:~$ conda list
# packages in environment at /projects/academic/tkrabben/modules_KrabLab/easybuild/2023.01/software/Core/miniconda3/22.11.1-1/envs/puzzle-hi-c-deps:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
biopython                 1.78             py39h3811e60_2    conda-forge
bzip2                     1.0.8                hd590300_5    conda-forge
c-ares                    1.26.0               hd590300_0    conda-forge
ca-certificates           2023.11.17           hbcca054_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
h5py                      3.7.0           nompi_py39h817c9c5_102    conda-forge
hdf5                      1.12.2          nompi_h4df4325_101    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.21.2               h659d440_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
libaec                    1.1.2                h59595ed_1    conda-forge
libblas                   3.9.0           21_linux64_openblas    conda-forge
libcblas                  3.9.0           21_linux64_openblas    conda-forge
libcurl                   8.5.0                hca28451_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.2.0               h807b86a_4    conda-forge
libgfortran-ng            13.2.0               h69a702a_4    conda-forge
libgfortran5              13.2.0               ha4646dd_4    conda-forge
libgomp                   13.2.0               h807b86a_4    conda-forge
liblapack                 3.9.0           21_linux64_openblas    conda-forge
libnghttp2                1.58.0               h47da74e_1    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libopenblas               0.3.26          pthreads_h413a1c8_0    conda-forge
libsqlite                 3.44.2               h2797004_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_4    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
ncurses                   6.4                  h59595ed_2    conda-forge
networkx                  2.8.4              pyhd8ed1ab_0    conda-forge
numpy                     1.26.3           py39h474f0d3_0    conda-forge
openssl                   3.2.1                hd590300_0    conda-forge
pandas                    1.5.1            py39h4661b88_1    conda-forge
pip                       23.3.2             pyhd8ed1ab_0    conda-forge
python                    3.9.18          h0755675_1_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.9                      4_cp39    conda-forge
pytz                      2023.4             pyhd8ed1ab_0    conda-forge
readline                  8.2                  h8228510_1    conda-forge
setuptools                69.0.3             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tqdm                      4.64.1             pyhd8ed1ab_0    conda-forge
tzdata                    2023d                h0c530f3_0    conda-forge
wheel                     0.42.0             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zstd                      1.5.5                hfc55251_0    conda-forge
```

**Comment by linguoliang** [comment]
Can you paste your commands here?
