### ISSUE TITLE
subprocess.CalledProcessError

### ISSUE THREAD

**Issue by PengfeiInTuebingen** [linguoliang/puzzle-hi-c#6]
Hi,
Thanks for developing this tool, i was trying to run this pipeline, i run juicer pipeline with my draft geneme first, then i used "merged_nodups.txt" for puzzle, I got an issue when doing the 9th interaction:
Reach the best with 7 Iterations
Traceback (most recent call last):
  File "/ebio/abt5_projects/3D_genome_of_brown_algae/data/software/puzzle-hi-c/main.py", line 1770, in <module>
    subprocess.run("rm {0}".format(contact_file.format(iteration - 1)), shell=True, check=True,
  File "/ebio/abt5_projects/3D_genome_of_brown_algae/data/software/envs/odp/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'rm Chordaria_7.txt' returned non-zero exit status 1.
the command I used is: "python3 /ebio/abt5_projects/3D_genome_of_brown_algae/data/software/puzzle-hi-c/main.py -c 27 -p Chordaria -s 10000 -t 0.35 -i 6 -m ../aligned/merged_nodups.txt -f ../Chordaria-linearis.fa -j /ebio/abt5_projects/software/code/miniconda3/envs/Hi-C_scaffolding/bin/juicer_tools -n 35"
Do you have solution for this?
Best,
Pengfei

**Comment by linguoliang** [comment]
> Hi, Thanks for developing this tool, i was trying to run this pipeline, i run juicer pipeline with my draft geneme first, then i used "merged_nodups.txt" for puzzle, I got an issue when doing the 9th interaction: Reach the best with 7 Iterations Traceback (most recent call last): File "/ebio/abt5_projects/3D_genome_of_brown_algae/data/software/puzzle-hi-c/main.py", line 1770, in subprocess.run("rm {0}".format(contact_file.format(iteration - 1)), shell=True, check=True, File "/ebio/abt5_projects/3D_genome_of_brown_algae/data/software/envs/odp/lib/python3.9/subprocess.py", line 528, in run raise CalledProcessError(retcode, process.args, subprocess.CalledProcessError: Command 'rm Chordaria_7.txt' returned non-zero exit status 1. the command I used is: "python3 /ebio/abt5_projects/3D_genome_of_brown_algae/data/software/puzzle-hi-c/main.py -c 27 -p Chordaria -s 10000 -t 0.35 -i 6 -m ../aligned/merged_nodups.txt -f ../Chordaria-linearis.fa -j /ebio/abt5_projects/software/code/miniconda3/envs/Hi-C_scaffolding/bin/juicer_tools -n 35" Do you have solution for this? Best, Pengfei

Thank you for reporting this bug! We now fixed this bug! Pleased downlaod the latest version!
