### ISSUE TITLE
no PBS dir

### ISSUE THREAD

**Issue by ericgonzalezs** [linguoliang/puzzle-hi-c#9]
Hi,

I downloaded juicer 1.5.6 from here https://github.com/aidenlab/juicer/releases/tag/1.5.6

There are only the next directories in this version:
AWS  CPU  LICENSE  LSF  misc  README.md  SLURM  UGER

However that release does not include the directory PBS. Do I have to download the last juicer version?

Thanks!

Eric

**Comment by ericgonzalezs** [comment]
I used the latest verision and I am having the next error:

processing links
iteration:9
Processing Iter 10!
Reach the best!
Traceback (most recent call last):
  File "/home/egonza02/scratch/SOFTWARE/PUZZEL_HIC/puzzle-hi-c/main.py", line 1789, in <module>
    subprocess.run("{0} pre {1} {2}.hic {3}".format(juicer_tools,
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.9.6/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '{Juicer}/PBS/scripts/juicer_tools pre Harg2202_HIC_oldhifiasm.hic.hap1.txt.re.sort Harg2202_HIC_oldhifiasm.hic.hap1.hic Harg2202_HIC_oldhifiasm.hic.hap1.Chrom.sizes' returned non-zero exit status 127.

**Comment by linguoliang** [comment]
Thanks,note that we cannot test PBS

> Hi,
> 
> I downloaded juicer 1.5.6 from here https://github.com/aidenlab/juicer/releases/tag/1.5.6
> 
> There are only the next directories in this version: AWS CPU LICENSE LSF misc README.md SLURM UGER
> 
> This does not include the directory PBS. Do I have to download the lates juicer version?
> 
> Thanks!
> 
> Eric
Hi Eric, you can change the parameter from -j {Juicer}/PBS/scripts/juicer_tools to -j {Juicer}/CPU/common/juicer_tools. This should work even with the version you downloaded (1.5.6). Let me know if you encounter any other issues!

**Comment by linguoliang** [comment]
> I used the latest verision and I am having the next error:
> 
> processing links iteration:9 Processing Iter 10! Reach the best! Traceback (most recent call last): File "/home/egonza02/scratch/SOFTWARE/PUZZEL_HIC/puzzle-hi-c/main.py", line 1789, in subprocess.run("{0} pre {1} {2}.hic {3}".format(juicer_tools, File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.9.6/lib/python3.9/subprocess.py", line 528, in run raise CalledProcessError(retcode, process.args, subprocess.CalledProcessError: Command '{Juicer}/PBS/scripts/juicer_tools pre Harg2202_HIC_oldhifiasm.hic.hap1.txt.re.sort Harg2202_HIC_oldhifiasm.hic.hap1.hic Harg2202_HIC_oldhifiasm.hic.hap1.Chrom.sizes' returned non-zero exit status 127.

Hi Eric, you can change the parameter from -j {Juicer}/PBS/scripts/juicer_tools to -j {Juicer}/CPU/common/juicer_tools. This should work even with the version you downloaded (1.5.6). Let me know if you encounter any other issues!

**Comment by linguoliang** [comment]
> {Juicer}

Sorry, there's a small mistake here: {Juicer} needs to have a $ symbol added, -j ${Juicer}/CPU/common/juicer_tools.
